version: '3.3'
services:
  nginx:
    image: nginx:latest
    container_name: "nginx"
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "80:80"
      - "443:443"
    restart: always
    working_dir: /var/www
    volumes:
      - /home/lean/projetos:/var/www/projetos/
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/webservers/:/etc/nginx/conf.d/
      - ./nginx/logs/Nginx:/var/log/nginx
    depends_on:
      - php-fpm-56
      - php-fpm-74
      - php-fpm-80
  php-fpm-56:
    container_name: "php-fpm-56"
    build: ./php/5.6/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /home/lean/projetos:/var/www/projetos/
      - ./php/5.6/config/php.ini:/usr/local/etc/php/php.ini
      - ./php/5.6/config/www.conf:/usr/local/etc/php-fpm.d/www.conf
  php-fpm-74:
    container_name: "php-fpm-74"
    build: ./php/7.4/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /home/lean/projetos:/var/www/projetos/
      - ./php/7.4/config/php.ini:/usr/local/etc/php/php.ini
      - ./php/7.4/config/www.conf:/usr/local/etc/php-fpm.d/www.conf
  php-fpm-80:
    container_name: "php-fpm-80"
    build: ./php/8.0/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /home/lean/projetos:/var/www/projetos/
      - ./php/8.0/config/php.ini:/usr/local/etc/php/php.ini
      - ./php/8.0/config/www.conf:/usr/local/etc/php-fpm.d/www.conf